// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trentoplaces.proto

package smartcampus.service.trento.places.data.message;

public final class Trentoplaces {
  private Trentoplaces() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlaceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // optional string street = 2;
    boolean hasStreet();
    String getStreet();
    
    // required string town = 3;
    boolean hasTown();
    String getTown();
    
    // optional string province = 4;
    boolean hasProvince();
    String getProvince();
    
    // optional string number = 5;
    boolean hasNumber();
    String getNumber();
    
    // optional double latitude = 6;
    boolean hasLatitude();
    double getLatitude();
    
    // optional double longitude = 7;
    boolean hasLongitude();
    double getLongitude();
    
    // repeated string categories = 8;
    java.util.List<String> getCategoriesList();
    int getCategoriesCount();
    String getCategories(int index);
    
    // required string source = 9;
    boolean hasSource();
    String getSource();
  }
  public static final class Place extends
      com.google.protobuf.GeneratedMessage
      implements PlaceOrBuilder {
    // Use Place.newBuilder() to construct.
    private Place(Builder builder) {
      super(builder);
    }
    private Place(boolean noInit) {}
    
    private static final Place defaultInstance;
    public static Place getDefaultInstance() {
      return defaultInstance;
    }
    
    public Place getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartcampus.service.trento.places.data.message.Trentoplaces.internal_static_smartcampus_service_trento_places_data_message_Place_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartcampus.service.trento.places.data.message.Trentoplaces.internal_static_smartcampus_service_trento_places_data_message_Place_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string street = 2;
    public static final int STREET_FIELD_NUMBER = 2;
    private java.lang.Object street_;
    public boolean hasStreet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          street_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string town = 3;
    public static final int TOWN_FIELD_NUMBER = 3;
    private java.lang.Object town_;
    public boolean hasTown() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTown() {
      java.lang.Object ref = town_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          town_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTownBytes() {
      java.lang.Object ref = town_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        town_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string province = 4;
    public static final int PROVINCE_FIELD_NUMBER = 4;
    private java.lang.Object province_;
    public boolean hasProvince() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getProvince() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          province_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string number = 5;
    public static final int NUMBER_FIELD_NUMBER = 5;
    private java.lang.Object number_;
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          number_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double latitude = 6;
    public static final int LATITUDE_FIELD_NUMBER = 6;
    private double latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getLatitude() {
      return latitude_;
    }
    
    // optional double longitude = 7;
    public static final int LONGITUDE_FIELD_NUMBER = 7;
    private double longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getLongitude() {
      return longitude_;
    }
    
    // repeated string categories = 8;
    public static final int CATEGORIES_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList categories_;
    public java.util.List<String>
        getCategoriesList() {
      return categories_;
    }
    public int getCategoriesCount() {
      return categories_.size();
    }
    public String getCategories(int index) {
      return categories_.get(index);
    }
    
    // required string source = 9;
    public static final int SOURCE_FIELD_NUMBER = 9;
    private java.lang.Object source_;
    public boolean hasSource() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          source_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      street_ = "";
      town_ = "";
      province_ = "";
      number_ = "";
      latitude_ = 0D;
      longitude_ = 0D;
      categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      source_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTown()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStreetBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTownBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getProvinceBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNumberBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, latitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, longitude_);
      }
      for (int i = 0; i < categories_.size(); i++) {
        output.writeBytes(8, categories_.getByteString(i));
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getSourceBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStreetBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTownBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getProvinceBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNumberBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, latitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, longitude_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < categories_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(categories_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCategoriesList().size();
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSourceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.trento.places.data.message.Trentoplaces.Place parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smartcampus.service.trento.places.data.message.Trentoplaces.Place prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements smartcampus.service.trento.places.data.message.Trentoplaces.PlaceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartcampus.service.trento.places.data.message.Trentoplaces.internal_static_smartcampus_service_trento_places_data_message_Place_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartcampus.service.trento.places.data.message.Trentoplaces.internal_static_smartcampus_service_trento_places_data_message_Place_fieldAccessorTable;
      }
      
      // Construct using smartcampus.service.trento.places.data.message.Trentoplaces.Place.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        street_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        town_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        province_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartcampus.service.trento.places.data.message.Trentoplaces.Place.getDescriptor();
      }
      
      public smartcampus.service.trento.places.data.message.Trentoplaces.Place getDefaultInstanceForType() {
        return smartcampus.service.trento.places.data.message.Trentoplaces.Place.getDefaultInstance();
      }
      
      public smartcampus.service.trento.places.data.message.Trentoplaces.Place build() {
        smartcampus.service.trento.places.data.message.Trentoplaces.Place result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private smartcampus.service.trento.places.data.message.Trentoplaces.Place buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        smartcampus.service.trento.places.data.message.Trentoplaces.Place result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public smartcampus.service.trento.places.data.message.Trentoplaces.Place buildPartial() {
        smartcampus.service.trento.places.data.message.Trentoplaces.Place result = new smartcampus.service.trento.places.data.message.Trentoplaces.Place(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.street_ = street_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.town_ = town_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.province_ = province_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.longitude_ = longitude_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          categories_ = new com.google.protobuf.UnmodifiableLazyStringList(
              categories_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.categories_ = categories_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.source_ = source_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartcampus.service.trento.places.data.message.Trentoplaces.Place) {
          return mergeFrom((smartcampus.service.trento.places.data.message.Trentoplaces.Place)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smartcampus.service.trento.places.data.message.Trentoplaces.Place other) {
        if (other == smartcampus.service.trento.places.data.message.Trentoplaces.Place.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasStreet()) {
          setStreet(other.getStreet());
        }
        if (other.hasTown()) {
          setTown(other.getTown());
        }
        if (other.hasProvince()) {
          setProvince(other.getProvince());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (!other.categories_.isEmpty()) {
          if (categories_.isEmpty()) {
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureCategoriesIsMutable();
            categories_.addAll(other.categories_);
          }
          onChanged();
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasTown()) {
          
          return false;
        }
        if (!hasSource()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              street_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              town_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              province_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              number_ = input.readBytes();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              latitude_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              longitude_ = input.readDouble();
              break;
            }
            case 66: {
              ensureCategoriesIsMutable();
              categories_.add(input.readBytes());
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              source_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional string street = 2;
      private java.lang.Object street_ = "";
      public boolean hasStreet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStreet(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        street_ = value;
        onChanged();
        return this;
      }
      public Builder clearStreet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      void setStreet(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        street_ = value;
        onChanged();
      }
      
      // required string town = 3;
      private java.lang.Object town_ = "";
      public boolean hasTown() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTown() {
        java.lang.Object ref = town_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          town_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTown(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        town_ = value;
        onChanged();
        return this;
      }
      public Builder clearTown() {
        bitField0_ = (bitField0_ & ~0x00000004);
        town_ = getDefaultInstance().getTown();
        onChanged();
        return this;
      }
      void setTown(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        town_ = value;
        onChanged();
      }
      
      // optional string province = 4;
      private java.lang.Object province_ = "";
      public boolean hasProvince() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getProvince() {
        java.lang.Object ref = province_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProvince(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        province_ = value;
        onChanged();
        return this;
      }
      public Builder clearProvince() {
        bitField0_ = (bitField0_ & ~0x00000008);
        province_ = getDefaultInstance().getProvince();
        onChanged();
        return this;
      }
      void setProvince(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        province_ = value;
        onChanged();
      }
      
      // optional string number = 5;
      private java.lang.Object number_ = "";
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        number_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      void setNumber(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        number_ = value;
        onChanged();
      }
      
      // optional double latitude = 6;
      private double latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000020;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000020);
        latitude_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double longitude = 7;
      private double longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000040;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      
      // repeated string categories = 8;
      private com.google.protobuf.LazyStringList categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          categories_ = new com.google.protobuf.LazyStringArrayList(categories_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getCategoriesList() {
        return java.util.Collections.unmodifiableList(categories_);
      }
      public int getCategoriesCount() {
        return categories_.size();
      }
      public String getCategories(int index) {
        return categories_.get(index);
      }
      public Builder setCategories(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
        categories_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addCategories(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllCategories(
          java.lang.Iterable<String> values) {
        ensureCategoriesIsMutable();
        super.addAll(values, categories_);
        onChanged();
        return this;
      }
      public Builder clearCategories() {
        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addCategories(com.google.protobuf.ByteString value) {
        ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
      }
      
      // required string source = 9;
      private java.lang.Object source_ = "";
      public boolean hasSource() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSource(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
        return this;
      }
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000100);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      void setSource(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:smartcampus.service.trento.places.data.message.Place)
    }
    
    static {
      defaultInstance = new Place(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:smartcampus.service.trento.places.data.message.Place)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcampus_service_trento_places_data_message_Place_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smartcampus_service_trento_places_data_message_Place_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022trentoplaces.proto\022.smartcampus.servic" +
      "e.trento.places.data.message\032\ncore.proto" +
      "\"\236\001\n\005Place\022\014\n\004name\030\001 \002(\t\022\016\n\006street\030\002 \001(\t" +
      "\022\014\n\004town\030\003 \002(\t\022\020\n\010province\030\004 \001(\t\022\016\n\006numb" +
      "er\030\005 \001(\t\022\020\n\010latitude\030\006 \001(\001\022\021\n\tlongitude\030" +
      "\007 \001(\001\022\022\n\ncategories\030\010 \003(\t\022\016\n\006source\030\t \002(" +
      "\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_smartcampus_service_trento_places_data_message_Place_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_smartcampus_service_trento_places_data_message_Place_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smartcampus_service_trento_places_data_message_Place_descriptor,
              new java.lang.String[] { "Name", "Street", "Town", "Province", "Number", "Latitude", "Longitude", "Categories", "Source", },
              smartcampus.service.trento.places.data.message.Trentoplaces.Place.class,
              smartcampus.service.trento.places.data.message.Trentoplaces.Place.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
